#!/bin/bash
#PBS -N ViT_flow_past_cylinder
#PBS -q gpu
#PBS -l select=1:host=node9:ncpus=1:ngpus=1
#PBS -o $USER_DIR/Mafaz/Projects/Machine\ Vision\ Transformer/ViT_flow_past_cylinder.out
#PBS -e $USER_DIR/Mafaz/Projects/Machine\ Vision\ Transformer/ViT_flow_past_cylinder.err

cd "$PBS_O_WORKDIR"

source $USER_DIR/Mafaz/myenv/bin/activate

export CUDA_VISIBLE_DEVICES="$NODE9_MIG_UUID"

echo "Job started on $(hostname) at $(date)"
python3 -m training.train 
echo "Job finished at $(date)"